routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*las dos siguientes rutas se han creado para el servicio de envio de notificaciones por correo*/
Route::post('send', ['as' => 'send', 'uses' => 'HomeController@send'] );
Route::get('contact', ['as' => 'contact', 'uses' => 'HomeController@contact'] );

Route::get('/set_language/{lang}','Controller@setLanguage')->name('set_language');
Route::get('login/{driver}','Auth\LoginController@redirectToProvider')->name('social_auth');
Route::get('login/{driver}/callback','Auth\LoginController@handleProviderCallback');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
//creamos un grupo de rutas, el cual nos permite realizar un conjunto de acciones
Route::group(['prefix' => 'courses'], function(){
	Route::get('/{course}','CourseController@show')->name('courses.detail');
	//Route::get('/{courses}','CourseController@show')->name('courses.detail2');
});

Route::group(['prefix' => 'subscriptions' ],function(){
	Route::get('/plans','SubscriptionController@plans')
	->name('subscriptions.plans');
	Route::post('/process_subscription','subscriptionController@processSubscription')
	->name('subscriptions.process_subscription');
});
Route::get('/images/{path}/{attachment}', function($path, $attachment) {
	$file = sprintf('storage/%s/%s', $path, $attachment);
	if(File::exists($file)) {
		return Image::make($file)->response();
	}
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Course;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //se ejecuta antes que cualquier otro proceso
        //y protege nuestra apliación a través de autenticación
        //podemos agregar una excepción
        //$this->middleware('auth')->except('index');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //acedemos a todos los cursos paginaodos y en estado pubicado
        $courses = Course::withCount(['students'])
            ->with('category','teacher','reviews')
            ->where('status',Course::PUBLISHED)
            ->latest()
            ->paginate(10);
            //dd($courses);
        return view('home',compact('courses'));
    }

    public function send(Request $request)
   {
       //guarda el valor de los campos enviados desde el form en un array
       $data = $request->all();

       //se envia el array y la vista lo recibe en llaves individuales {{ $email }} , {{ $subject }}...
       \Mail::send('mails.enviar_notificaciones', $data, function($message) use ($request)
       {
           //remitente
           $message->from($request->email, $request->name);

           //asunto
           $message->subject($request->subject);

           //receptor
           $message->to('valz.henk@gmail.com', 'nombre de usuario');

           $message->cc('henry_valz@hotmail.com','mensaje en copia');
           $message->bcc('kvalero@cenepred.gob.pe','mensaje en copia oculta');

       });
       return \View::make('success');
   }

   public function contact(){
    return \View::make('contact');
   }
}

resources/views/partials/courses/action_button.blade.php
<div class="col-2">
	@auth
		@can('opt_for_course', $course)
             @can('subscribe', \App\Course::class)
             {{-- puede suscribrise a la plataforma de pago --}}
				<a style="white-space: normal;" class="btn btn-subscribe btn-bottom btn-block" href="{{ route('subscriptions.plans') }}">
					<i class="fa fa-bolt"></i>{{__("Subscribirme y acceder")}}
				</a>
			@else
				@can('inscribe',$course)
				{{--  el usuario suscrito puede inscribirse al curso--}}
				<a style="white-space: normal;" class="btn btn-subscribe btn-bottom btn-block" href="#">
					<i class="fa fa-bolt"></i>{{__("Inscribirme")}}
				</a>				
				@else
				<a style="white-space: normal;" class="btn btn-subscribe btn-bottom btn-block" href="#">
					<i class="fa fa-bolt"></i>{{__("Inscrito")}}
				</a>
				@endcan
			@endcan
		@else
			<a class="btn btn-subscribe btn-bottom btn-block" style="white-space: normal;" href="#">
				<i class="fa fa-user"></i>{{__("Soy autor")}}
			</a>
		@endcan
	@else
			<a class="btn btn-subscribe btn-bottom btn-block" style="white-space: normal;" href="{{ route('login')}}">
				<i class="fa fa-user"></i>{{__("Acceder")}}
			</a>
	@endauth
</div>

resources/views/partials/courses/card_course.blade.php
<div class="card card-01">
    <img
        class="card-img-top"
        src="{{ $course->pathAttachment() }}"
        alt="{{ $course->name }}"
    />
    <div class="card-body">
        <span class="badge-box"><i class="fa fa-check"></i></span>
        <h4 class="card-title">{{ $course->name }}</h4>
        <hr />
        <div class="row justify-content-center">
            @include('partials.courses.rating', ['rating' => $course->custom_rating])

        </div>
        <hr />
        <span class="badge badge-danger badge-cat">{{ $course->category->name }}</span>
        <p class="card-text">
            {{ str_limit($course->description, 100) }}
        </p>
        <a
            href="{{ route('courses.detail',$course->id) }}"
            class="btn btn-course btn-block"
        >
            {{ __("Más información") }}
        </a>
    </div>
</div>

resources/views/partials/courses/description.blade.php
<div class="col-12 pt-0 mt-0">
	<h2 class="text-muted">{{__("Que vamos a hacer?")}}</h2>
	<hr />
</div>
	<div class="col-12">
			<p class="mb-0">
				{{$course->description}}
			</p>
	</div>

resources/views/partials/courses/goals.blade.php
<div class="col-12 pt-0 mt-0">
	<h2 class="text-muted">{{__("Metas del curso")}}</h2>
	<hr />
</div>
@forelse($goals as $goal)
{{--estos divs están siendo interpretados--}}
	<divGoals class="col-4">
		<div class="card bg-light p-3">
			<p class="mb-0">
				{{$goal->goal}}
			</p>
		</div>
	</divGoals>
@empty
	<div class="alert alert-dark">
		<i class="fa fa-info-circle"></i>
		{{__("No se ha escrito metas para este curso")}}
	</div>

@endforelse

resources/views/partials/courses/jumbotron.blade.php
<div class="row mb-4">
	<div class="col-md-12">
		<div class="card" style="background-image: url('{{ url('/images/jumbotron.png')  }}');">
			<div class="text-white text-center d-flex align-items-center py-5 px-4 my-5">
				<div class="col-5">
					<img class="img-fluid" src="../{{$course->pathAttachment()}}"/>
					
				</div>
				<div class="col-5 text-left">
					<h1>{{__("Curso")}}:{{$course->name}}</h1>
					<h4>{{__("Profesor")}}:{{$course->teacher->user->name}}</h4>
					<h4>{{__("Categoria")}}:{{$course->category->name}}</h4>
					<h4>{{__("Fecha de publicación")}}:{{$course->created_at->format('d/m/Y')}}</h4>
					<h4>{{__("Fecha de actualización")}}:{{$course->updated_at->format('d/m/Y')}}</h4>
					<h6>{{__("Estudiantes inscritos")}}:{{$course->students_count}}</h6>
					<h6>{{__("Número de valoraciones")}}:{{$course->reviews_count}}</h6>
					@include('partials.courses.rating', ['rating' => $course->custom_rating])
				</div>
				@include('partials.courses.action_button')
			</div>
		</div>
	</div>
</div>

resources/views/partials/courses/rating.blade.php
<div>
	<ul class="list-inline">
		<li class="list-inline-item"><i class="fa fa-star{{ $rating >= 1 ? ' yellow' : ''  }}"></i></li>
		<li class="list-inline-item"><i class="fa fa-star{{ $rating >= 2 ? ' yellow' : ''  }}"></i></li>
		<li class="list-inline-item"><i class="fa fa-star{{ $rating >= 3 ? ' yellow' : ''  }}"></i></li>
		<li class="list-inline-item"><i class="fa fa-star{{ $rating >= 4 ? ' yellow' : ''  }}"></i></li>
		<li class="list-inline-item"><i class="fa fa-star{{ $rating >= 5 ? ' yellow' : ''  }}"></i></li>
	</ul>
</div>

resources/views/partials/courses/related.blade.php
<div class="col-12 pt-0 mt-4">
	<h2 class="text-muted">
		{{__("Cursos similares")}}
	</h2>
	<hr />
</div>
<div class="container-fluid">
	<div class="row">
		@forelse($related as $relatedCourse)
		<div class="col-md-6 listing-block">
			<div class="media">
				<div class="fav-box">
					<i class="fa fa-heart-o" aria-hidden="true"></i>
				</div>
				<a href="{{ route('courses.detail',$relatedCourse->id) }}">
					<img class="d-flex align-self-start"
					src="../images/courses/{{$relatedCourse->picture}}" 
					alt="{{ $relatedCourse->name }}" />
				</a>
				<div class="media-body pl-3">
					<div class="price">
						<small>{{ $relatedCourse->name }}</small>
					</div>
					<div class="stats">
						@include('partials.courses.rating',['rating'=>$relatedCourse->custom_rating])
					</div>
				</div>
			</div>
		</div>
		@empty
			<div class="alert alert-dark">
				{{__("No existe ningún curso relacionado")}}
			</div>
		@endforelse
	</div>
</div>

resources/views/partials/courses/requirements.blade.php
<div class="col-12 pt-0 mt-0">
	<h2 class="text-muted">{{__("Requisitos para tomar el curso")}}</h2>
	<hr />
</div>
@forelse($requirements as $requirement)
	<div class="col-6">
		<div class="card bg-light p-3">
			<p class="mb-0">
				{{$requirement->requirement}}
			</p>
		</div>
	</div>
@empty
	<div class="alert alert-dark">
		<i class="fa fa-info-circle"></i>
		{{__("No hay ningún requisito para este curso")}}
	</div>

@endforelse